language: objective-c
osx_image: xcode9.2
skip_cleanup: true
env:
  global:
  - FRAMEWORK_NAME=PutKit
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: ipvqTB4Xj7lmq/UZOntuWxZWaV/akevzHarPd4sLbig1lhNFpzJVU22B1ozpzNXTGkzUHey08JQZkFQpVtOUpUpFKltfxdBO4Dp1y4x3kXNWAKGRZmv55b9QLkhzbteKXXZtlXyCXSlRCR9rIHOZD0wKgb7OGg4muLzh48ND6i3yEh/EOV9KJrCEVO+let8aYi+i5Wv7bRKkSb0izOtMkimNyxwXwrPqG0kfG5Qwj6mPxC4pGQyYB3GQ5rvR6qtDB+pf2wQUzQCnCA2rt3ZVuYzW1WG+Xce3G5KZjD3Qu0gtRHNmc3d2oFJ93QAHvFNEImWmNBKm2gSYE3joF2AraR3oJLR7ZZpKBTvZOPTk6me5v8kd0wA1zPRhpf4gqJnZBoDVHdsbQiulzRig302o0Yuh5JxBUyU9H4HTUp1+NwQFIdd00IE0YMNcKcqC9MXwF660cRCrPuqWHtArj4XJxRwrZGZrMPhoSLEZZRp8SetJ+aj9eMRXivvaJZyhh7ORhJhZrbYlUM8p+XrakNk3JmyQVrddMZhQpqEE07WAao5xvy57B3Y9+SW1neZc2KYNemF2l4zZ6VcQEBsvqrBQyknCOpf+24GtywQ38Gvf1CRoah82irjsca3jmBIpG3BwKdLjC3/VhUlRGCvLpb729Vxcq/+0pww9fcTRoMbprRs=
  file: $FRAMEWORK_NAME.framework.zip
  on:
    repo: mourke/PutKit
notifications:
  email: false
